# Generated by Django 5.1 on 2025-11-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('happiness_rank', models.IntegerField()),
                ('happiness_score', models.DecimalField(decimal_places=5, max_digits=6)),
                ('standard_error', models.DecimalField(decimal_places=5, max_digits=6)),
                ('economy', models.DecimalField(decimal_places=5, max_digits=6)),
                ('family', models.DecimalField(decimal_places=5, max_digits=6)),
                ('health', models.DecimalField(decimal_places=5, max_digits=6)),
                ('freedom', models.DecimalField(decimal_places=5, max_digits=6)),
                ('trust', models.DecimalField(decimal_places=5, max_digits=6)),
                ('generosity', models.DecimalField(decimal_places=5, max_digits=6)),
                ('dystopia', models.DecimalField(decimal_places=5, max_digits=6)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_happiness.region')),
            ],
        ),
    ]


# quicksort algorithm
