# Generated by Django 3.1.1 on 2025-11-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_happiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='happiness_rank',
        ),
    ]
